/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

/**
 *
 * @author theus
 */
public class Munu_inicial extends javax.swing.JFrame {

    /**
     * Creates new form Munu_inicial
     */
    public Munu_inicial() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenuItem36 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Vews/Imagens/OIP (1).jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 493));

        jMenuBar1.setToolTipText("JMenu");

        jMenu1.setText("Cadastro");

        jMenuItem2.setText("Clientes");
        jMenuItem2.setToolTipText("");
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Produtos");
        jMenu1.add(jMenuItem3);

        jMenuItem4.setText("Contas");
        jMenuItem4.setToolTipText("");
        jMenu1.add(jMenuItem4);

        jMenuItem5.setText("Horarios");
        jMenu1.add(jMenuItem5);

        jCheckBoxMenuItem3.setSelected(true);
        jCheckBoxMenuItem3.setText("Fucionarios");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jCheckBoxMenuItem3);

        jMenuItem6.setText("Fornecedores");
        jMenuItem6.setToolTipText("Fornecedores");
        jMenu1.add(jMenuItem6);

        jMenu7.setText("Impostos");
        jMenu1.add(jMenu7);

        jMenuItem20.setText("Usuarios");
        jMenu1.add(jMenuItem20);

        jMenuItem29.setText("Contador");
        jMenu1.add(jMenuItem29);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Operação");

        jMenuItem1.setText("Estoque");
        jMenu2.add(jMenuItem1);

        jMenuItem7.setText("Inventario");
        jMenu2.add(jMenuItem7);

        jMenuItem8.setText("Funcionarios");
        jMenu2.add(jMenuItem8);

        jMenuItem9.setText("Vendas");
        jMenu2.add(jMenuItem9);

        jMenuItem10.setText("Manutenção");
        jMenu2.add(jMenuItem10);

        jMenuItem21.setText("Nivel De Acesso");
        jMenu2.add(jMenuItem21);

        jMenuItem34.setText("Site ");
        jMenu2.add(jMenuItem34);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Relatorios");

        jMenuItem11.setText("Vendas");
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Compras");
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Desenoenho");
        jMenu3.add(jMenuItem13);

        jMenuItem14.setText("Gastos");
        jMenu3.add(jMenuItem14);

        jMenuItem15.setText("Lucros ");
        jMenu3.add(jMenuItem15);

        jMenuItem16.setText("Impostos");
        jMenu3.add(jMenuItem16);

        jMenuItem27.setText("Financeiro");
        jMenu3.add(jMenuItem27);

        jMenuItem28.setText("Contabil");
        jMenu3.add(jMenuItem28);

        jMenuItem35.setText("Movimetação Site");
        jMenu3.add(jMenuItem35);

        jMenuItem36.setText("Movimentação Loja Fisica");
        jMenu3.add(jMenuItem36);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Agenda");

        jMenuItem17.setText("Agendamentos");
        jMenu4.add(jMenuItem17);

        jMenuItem18.setText("Clintes Fixos");
        jMenu4.add(jMenuItem18);

        jMenuItem19.setText("Horaios disponiveis");
        jMenu4.add(jMenuItem19);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Financeiro");

        jMenuItem22.setText("Constas A Pagar");
        jMenu5.add(jMenuItem22);

        jMenuItem23.setText("Contas A Receber");
        jMenu5.add(jMenuItem23);

        jMenuItem24.setText("Nfe Fornacedores");
        jMenu5.add(jMenuItem24);

        jMenuItem25.setText("Nfe de Pagamentos");
        jMenu5.add(jMenuItem25);

        jMenuItem26.setText("Contatbiliade");
        jMenu5.add(jMenuItem26);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("E-Commerce");

        jMenuItem30.setText("Site ");
        jMenu6.add(jMenuItem30);

        jMenuItem31.setText("Sheein");
        jMenu6.add(jMenuItem31);

        jMenuItem32.setText("Shoppe");
        jMenu6.add(jMenuItem32);

        jMenuItem33.setText("Marketing-place");
        jMenu6.add(jMenuItem33);

        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Munu_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Munu_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Munu_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Munu_inicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Munu_inicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem36;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
}
